# Automatically generated by Pynguin.
import httpie.models as module_0
import builtins as module_1


def test_case_0():
    bytes_0 = b""
    tuple_0 = (bytes_0,)
    str_0 = "8S55bL0BD704"
    h_t_t_p_request_0 = module_0.HTTPRequest(str_0)
    generator_0 = h_t_t_p_request_0.iter_lines(h_t_t_p_request_0)
    set_0 = {h_t_t_p_request_0, str_0}
    h_t_t_p_message_0 = module_0.HTTPMessage(set_0)
    h_t_t_p_response_0 = module_0.HTTPResponse(h_t_t_p_message_0)
    h_t_t_p_response_0.iter_lines(tuple_0)


def test_case_1():
    str_0 = "W([V.<"
    dict_0 = {}
    h_t_t_p_request_0 = module_0.HTTPRequest(dict_0)
    h_t_t_p_response_0 = module_0.HTTPResponse(h_t_t_p_request_0)
    h_t_t_p_request_1 = module_0.HTTPRequest(h_t_t_p_response_0)
    generator_0 = h_t_t_p_request_1.iter_lines(str_0)
    str_1 = "wL&>e"
    h_t_t_p_response_1 = module_0.HTTPResponse(str_1)
    h_t_t_p_response_1.iter_body()


def test_case_2():
    bytes_0 = b"IC\x87\xe3\xeb=5~\x9d\x19\xba;\xc3*d\xa6H\xfe\x9e\xcf"
    h_t_t_p_message_0 = module_0.HTTPMessage(bytes_0)
    dict_0 = {}
    none_type_0 = None
    h_t_t_p_request_0 = module_0.HTTPRequest(dict_0)
    generator_0 = h_t_t_p_request_0.iter_lines(none_type_0)
    h_t_t_p_request_1 = module_0.HTTPRequest(none_type_0)
    h_t_t_p_response_0 = module_0.HTTPResponse(none_type_0)
    h_t_t_p_response_0.iter_body()


def test_case_3():
    str_0 = "[i7ej=fPc/a"
    h_t_t_p_message_0 = module_0.HTTPMessage(str_0)
    h_t_t_p_message_0.iter_body(h_t_t_p_message_0)


def test_case_4():
    str_0 = "~h1Of^wY9{\n&Yx"
    h_t_t_p_response_0 = module_0.HTTPResponse(str_0)
    h_t_t_p_request_0 = module_0.HTTPRequest(h_t_t_p_response_0)
    h_t_t_p_response_0.iter_body()


def test_case_5():
    none_type_0 = None
    h_t_t_p_request_0 = module_0.HTTPRequest(none_type_0)
    int_0 = -4555
    h_t_t_p_response_0 = module_0.HTTPResponse(int_0)
    float_0 = 1773.2
    h_t_t_p_response_1 = module_0.HTTPResponse(float_0)
    h_t_t_p_response_1.iter_lines(h_t_t_p_response_1)


def test_case_6():
    str_0 = "I\x0b)bk,v6VP\x0bWsPe3\rvTl"
    h_t_t_p_message_0 = module_0.HTTPMessage(str_0)
    set_0 = set()
    h_t_t_p_response_0 = module_0.HTTPResponse(set_0)
    list_0 = [set_0]
    h_t_t_p_request_0 = module_0.HTTPRequest(set_0)
    h_t_t_p_message_1 = module_0.HTTPMessage(list_0)
    h_t_t_p_message_1.iter_lines(set_0)


def test_case_7():
    int_0 = -3180
    h_t_t_p_request_0 = module_0.HTTPRequest(int_0)
    int_1 = -751
    h_t_t_p_request_1 = module_0.HTTPRequest(int_1)
    generator_0 = h_t_t_p_request_1.iter_body(int_0)
    module_1.object(*generator_0)


def test_case_8():
    none_type_0 = None
    h_t_t_p_request_0 = module_0.HTTPRequest(none_type_0)
    h_t_t_p_response_0 = module_0.HTTPResponse(h_t_t_p_request_0)
    int_0 = 4
    h_t_t_p_request_1 = module_0.HTTPRequest(h_t_t_p_response_0)
    generator_0 = h_t_t_p_request_1.iter_lines(int_0)
    module_1.object(*generator_0)
